server:
    port: 8081

spring:
    application:
        name: memory-impl

    ai:
        ollama:
            base:
                url: http://localhost:11434
            chat:
                options:
                    model: codellama
                    temperature: 0.7

    datasource:
        url: jdbc:mysql://localhost:3306/ai_chat_memory
        username: root
        password: root



logging:
    level:
        org.springframework.ai.chat.client.advisor: DEBUG